# 애플리케이션 기본 정보
spring:
  application:
    name: pr1mary

  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 30MB

# 서버 설정
server:
  port: 8080

# 파일 업로드 경로
file:
  path-student: /studentImage
  path-teacher: /teacherImage